### ISSUE TITLE
general rules and objectives

### ISSUE THREAD

**Issue by Torpus** [Torpus/breadsticks#2]
cross-platform (linux, windows, osx) compatible

**Comment by Torpus** [comment]
cross-architecture (x86, amd64, arm) compatible

**Comment by Torpus** [comment]
@cujarrett @circa10a @seemanth

**Comment by circa10a** [comment]
Thinking only execute on Travis or would that leave too much room for inconsistencies

**Comment by Torpus** [comment]
hmmm, how does travis allocate resources?  would it be consistent across runs?

**Comment by Torpus** [comment]
could do a fresh install of both windows and linux on my laptop but wouldn't be able to cover osx

**Comment by circa10a** [comment]
Looks like it would be
https://docs.travis-ci.com/user/reference/overview/

Should probably just stick to Linux amd64 builds for consistency

**Comment by Torpus** [comment]
i'm ok with that
